### PR TITLE
Adjusted models; transcript now works much better.

### PR DESCRIPTION
**Pull request by duane**
I pulled out Course from Section. The transcript page now works nearly correctly; we just need to do the letter grade => unit conversion to calculate the gpa.

### CODE REVIEW

**Comment by duane** [comment]
:clock1: :clock2: :clock3: :clock4: :clock5: :clock6: :clock7: :clock8: :clock9: :clock10: :clock11: :clock12:

**Comment by duane** [comment]
:arrow_lower_right: :arrow_lower_left:
:arrow_down: :arrow_down:

**Comment by nconlon** [comment]
when I enter an individual course, the Profile page crashes:

-Disregard, I was working off an older version!

**Comment by duane** [comment]
I can't reproduce Nick's error, and he's on an old revision, so I'm going to go ahead and merge this.

**Pull request merged**
